name: Build and Deploy Microsite

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies if a package.json exists. This step will not fail if no package.json is present.
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi
      # Build step placeholder (no build script for static microsite)
      - name: Build project
        run: |
          echo "No build step required for static site"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public